// <auto-generated />
namespace Sem3EProjectOnlineCPFH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addemailconformcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addemailconformcode));
        
        string IMigrationMetadata.Id
        {
            get { return "202503121626228_addemailconformcode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
